### ISSUE TITLE
To-Do list

### ISSUE THREAD

**Issue by UltimateMcraft** [UltimateMcraft/personalsite#1]
- [x] Find out how to open .otf files
- [ ] Upload the file

- [ ] Find out how to open .eot files
- [ ] Upload the files

- [ ] Find out how to open .ttf files
- [ ] Upload the file

- [ ] Find out how to open .woff files
- [ ] Upload the file

**Comment by UltimateMcraft** [comment]
Update: I found out how to open them but I won't upload them till later

**Comment by UltimateMcraft** [comment]
.eot file is corrupt, it probably won't be needed so I won't upload it
